# Generated by Django 4.2.10 on 2024-02-21 13:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def strip_acme_prefix(apps, schema_editor):
    Domain = apps.get_model("api", "Domain")
    for domain in Domain.objects.all():
        if domain.fqdn.startswith("_acme-challenge."):
            domain.fqdn = domain.fqdn.removeprefix("_acme-challenge.")
            domain.save(update_fields=["fqdn"])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fqdn",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_fqdn",
                                message="Enter a valid FQDN.",
                                regex=r"(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}$)",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DomainUserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        max_length=20,
                        choices=[
                            ("DOMAIN", "domain"),
                            ("SUBDOMAIN", "subdomain"),
                        ],
                        default="DOMAIN",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.domain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(strip_acme_prefix),
    ]
