# Generated by Django 5.2.4 on 2025-08-04 08:52

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def strip_acme_prefix(apps, schema_editor):
    Domain = apps.get_model("api", "Domain")
    for domain in Domain.objects.all():
        if domain.fqdn.startswith("_acme-challenge."):
            domain.fqdn = domain.fqdn.removeprefix("_acme-challenge.")
            domain.save(update_fields=["fqdn"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="domainuserpermission",
            name="access_level",
            field=models.CharField(
                choices=[("subdomain", "Subdomain"), ("domain", "Domain")], default="domain"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="domainuserpermission",
            name="text",
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="fqdn",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_fqdn",
                        message="Enter a valid FQDN.",
                        regex="(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\\.)+[a-zA-Z]{2,63}$)",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="domainuserpermission",
            constraint=models.UniqueConstraint(
                fields=("user", "domain", "access_level"), name="unique_user_domain_accesslevel"
            ),
        ),
        migrations.RunPython(strip_acme_prefix),
    ]
