name: Build Rock and Charm

on:
  pull_request:

jobs:
  build-rock:
    name: Build Rock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: weiiwang01/rockcraft
          ref: feat-12f-django
          path: rockcraft

      - uses: canonical/setup-lxd@v0.1.1

      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Build and Install Rockcraft
        working-directory: ./rockcraft
        run: |
          snapcraft --use-lxd
          snap install --dangerous --classic rockcraft*.snap
          cp rockcraft*.snap ../

      - uses: actions/upload-artifact@v4
        with:
          name: rockcraft-snap
          path: "rockcraft*.snap"

      - name: Cleanup
        run: rm -rf rockcraft*

      - uses: actions/checkout@v4

      - name: Build Rock
        env:
          ROCKCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: "true"
        run: rockcraft pack --verbosity trace

      - name: Print Rockcraft logs
        if: always()
        run: "cat ~/.local/state/rockcraft/log/* || :"

      - uses: actions/upload-artifact@v4
        with:
          name: rock
          path: "*.rock"

  build-charm:
    name: Build Charm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: weiiwang01/charmcraft
          ref: feat-12f-django
          path: charmcraft

      - uses: canonical/setup-lxd@v0.1.1

      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Build and Install Charmcraft
        working-directory: ./charmcraft
        run: |
          snapcraft --use-lxd
          snap install --dangerous --classic charmcraft*.snap
          cp charmcraft*.snap ../

      - uses: actions/upload-artifact@v4
        with:
          name: charmcraft-snap
          path: "charmcraft*.snap"

      - name: Cleanup
        run: rm -rf charmcraft*

      - uses: actions/checkout@v4

      - name: Build Charm
        env:
          CHARMCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: "true"
        run: charmcraft pack --verbosity trace

      - name: Print Charmcraft logs
        if: always()
        run: "cat ~/.local/state/charmcraft/log/* || :"

      - uses: actions/upload-artifact@v4
        with:
          name: charm
          path: "*.charm"
